[build-system]
requires = ["setuptools>=65.0"]
build-backend = "setuptools.build_meta"

[project]
name = "cowexcept"
version = "1.4.0"
description = "Spice up those exceptions with cowexcept!"
authors = [{ name = "James Finnie-Ansley", email = "james@ansley.dev" }]
readme = "README.md"
requires-python = ">=3.10"
license = "Apache-2.0"
keywords = ["cowsay"]
dependencies = ["python-cowsay>=1.2.2"]

[project.urls]
repository = "https://codeberg.org/jamesansley/cowexcept"
